### ISSUE TITLE
Should we use `tentaclio` to enable remote URIs

### ISSUE THREAD

**Issue by DBCerigo** [datavaluepeople/kotsu#16]
`store` currently can only write the validation results dataframe locally. If we switched to using `tentaclio` it could be a cloud storage bucket. 
https://github.com/datavaluepeople/kotsu/blob/703d551db9723e83d38749780b53017919617a30/kotsu/store.py#L19

The only downside I see of using `tentaclio` directly within the module is it significantly bloats the dependencies what is currently a pure python package :(

I think probably we shouldn't use it. I think if we wanted to enable that we could pass in an IO buffer/file handler directly into `kotsu` if a user wanted to use a remote/cloud store.

**Comment by andrewsutjahjo** [comment]
I'm leaning more towards using tentaclio. Having sharable validations by being able to say `using these datasets and these models I get these scores, run it yourself and try to find a better model using the same validation set` and reduce the barrier for trying sounds worth it to me to not have a pure python package.

**Comment by DBCerigo** [comment]
Having shareable validations, i.e. validations which read data in from a remote URI, is doable with kotsu in its current form. Kotsu doesn't add any restrictions on what goes on inside a validation, so if a validation wants to use `tentaclio` is can do that already. 

The only bit kotsu can't do, is store the results summary to a remote URI, because that's the only output kotsu actually writes.

**Comment by DBCerigo** [comment]
Given we're talking about removing `pandas` and then it would be a pure python package, then am closing this with conclusion "no" to tentaclio

**Comment by benjamincerigo** [comment]
I would agree that making the configuration of the store functions such as supporting a file handle would be more useful than trying to implement all the options needed. 

Might also be worth thinking about making the store functionality a function that can be passed to the run?

Or you could make a larger change:
- Remove the write from the run and return the result. 
- Have some default store functionality that users can use to write the result. 
- If they want to store it in another way they can write some other store functionality.

**Comment by DBCerigo** [comment]
> I would agree that making the configuration of the store functions such as supporting a file handle would be more useful than trying to implement all the options needed.
> 
> Might also be worth thinking about making the store functionality a function that can be passed to the run?
> 
> Or you could make a larger change:
> 
>     * Remove the write from the run and return the result.
> 
>     * Have some default store functionality that users can use to write the result.
> 
>     * If they want to store it in another way they can write some other store functionality.

@benjamincerigo I added this to #19 also
