### ISSUE TITLE
Need solution for workflow when developing models

### ISSUE THREAD

**Issue by DBCerigo** [datavaluepeople/kotsu#27]
Current flow is:
- write new model
- register it 
- run `run`
- find a bug in your registered model

Now you're in the state that you have a registered model that breaks and you can't get rid of. OR you have results for a model id that now won't re-run for that model id when you want it to. 

Probably want a util function like: 
```
erase_model(model_id: str, model_registry: ModelRegistry, results_path: str)
```

**Comment by DBCerigo** [comment]
Thought 1: I think raising an exception when registering a model/something with the same id is over kill, in the same way that python doesn't stop you from doing rash stuff/making mistakes, that it's up to the user to be responsible about it all. So instead of raising I suggest we log a WARNING.

**Comment by DBCerigo** [comment]
Thought 2: I don't like the `erase_model` - it adds another whole interface, I'd prefer to keep to just `run` if possible. So I suggest adding the following param to `run`:
```
Args:
...
    force_rerun (List[str]): A list of model ID's for which to force re running of validations for, even if prior results found, and over write prior results we new results. Useful for doing active development on a model in an interactive dev environment (i.e. Jupyter notebook). 
...
```

**Comment by DBCerigo** [comment]
I think implementing these two thoughts would solve the model development pains points. @alex-hh @ali-tny ?

**Comment by ali-tny** [comment]
sounds good to me - agree about allowing reregistering, and force_rerun sounds good as well if you wanna keep the interface to `run`. one suggestion: `force_rerun (Union[Literal["all"], List[str]])`

**Comment by DBCerigo** [comment]
@ali-tny `force_rerun (Union[Literal["all"], List[str]])` would then `replace skip_if_prior_result (bool)` entirely right?
