### ISSUE TITLE
Should work better for (pos) common pattern to store validation level artefacts separately from validation-model level?

### ISSUE THREAD

**Issue by DBCerigo** [datavaluepeople/kotsu#29]
Could think about passing in the validation level path and the validation-model level path in, that way the internal validation doesn't need to know so much about how the path is formed.

**Comment by DBCerigo** [comment]
Further explainer:
- in #39, if `artefacts_store_directory` is set, then all instantiated validations will be passed kwarg `artefacts_store_directory`
- Some artefacts are the same for validation-model combinations for a fixed validation, e.g. the input training data for each fold is the same for all models for that validation. Thus is is better to store a single copy at a "validation level path" rather than duplicate storing them for all "validation-model level path"s. 
- To get around then, a validation can do it's own manipulation of the `artefacts_store_directory` path, to get the validation level path and use that. BUT this means that the validation then has to do path manipulation and be more coupled to `kotsu.run`, so if something changes in `run` that alters the way the path is formed then that might require altering something in the validation. 

Thinking on a solution: 
- change the implicit `artefacts_store_directory` into `validation_artefacts_directory` and `model_artefacts_directory`. These would be passed to validations if `artefacts_store_directory` is not None. This way things are simpler for validations, and urls/paths are controlled more by `run`. 

I think I like this solution, though one could argue the other way, that this reduces the flexibility and scope of what is possible to do in a validation. The other solution may be to pass the `validation_id` and `model_id` to validations and let them do all of their own path forming and manipulation - this would make for the explicitly most flexible version.

**Comment by ali-tny** [comment]
- i like passing a place to store results to the validation, saving a bunch of boring path manipulation shite where you forget a trailing slash etc
- splitting it in two i think is a good idea
- could revisit `context` or something variable that can be passed to validations, which is a dict that holds shit relevant to the context that the validation is running in (eg has a key `validation_artefacts_directory`)

**Comment by DBCerigo** [comment]
Yea cool. The split it is then. And yea I think `context` is going to pop out naturally at some point in the future.
