### ISSUE TITLE
Implement something good for `nondeterministic=True`

### ISSUE THREAD

**Issue by DBCerigo** [datavaluepeople/kotsu#42]
This could be either because of stochasticity in the model/validation, or likely more needed/pertinent/interesting is validations that want to always run on some "latest" data, like in the case for Phoenix.

I think likely we will want to rerun val-model combos that have a `nondeterminisitc=True` every time even if already has a result for that combo, and then end user will need to look at most recent results using run datetime.

**Comment by alex-hh** [comment]
What is the use-case for having nondeterministic models/evaluations? Are there any situations in which nondeterministic model/validation are advisable?

If this flag ultimately functions only to determine that these combos are always re-run, then maybe we should rename from nondeterministic to always_rerun or something? Not sure what a setting where you'd want to use that would be but there might be some?
