### ISSUE TITLE
Make `run` return `results_df` for immediate in memory usage

### ISSUE THREAD

**Issue by DBCerigo** [datavaluepeople/kotsu#48]
A request from @TNTran92. 

@alex-hh @ali-tny: 
This would be a one line change, `return results_df` at https://github.com/datavaluepeople/kotsu/blob/7b184b1c6f48b779451ba95e353f7c74ec23574c/kotsu/run.py#L103
More a question of do we want to do this? Do we perceive any downsides?

**Comment by alex-hh** [comment]
Sounds like a good idea to me
